name: Cargo Audit
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch: null
jobs:
  audit:
    if: github.repository_owner == 'a-scie'
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Cargo audit (for security vulnerabilities)
        run: |
          cargo install --locked cargo-audit
          cargo audit
